name: Build and Push Docker Image (If Changed)

on:
  push:
    branches: [main]
    paths:
      - Dockerfile
      - .github/workflows/build_docker_container.yml

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # required for GHCR
      id-token: write  # optional if using OIDC auth

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .devcontainer/unit_tests/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/music_player_unit_tests:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
