name: Clang-Tidy

on: push

permissions:
  contents: read
  packages: read  # Needed to pull from GHCR if private


jobs:
  clang-tidy-check:
    runs-on: ubuntu-24.04

    container:
      image: ghcr.io/hitthesurf/music_player/unit_tests:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Clang Tidy
      run: cd scripts && ./clang_tidy_check.sh unit-tests.gcc.linux

