name: Run-Unit-Tests

on: push

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build And Run Unit Tests
      run: cd scripts && ./build_and_run_tests.sh unit-tests.gcc.linux
